# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shopping_Cart' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Shopping_Cart
    pod 'SDWebImage', '~> 4.0'
    pod 'AFNetworking', '~> 3.0'
end
